# Schema for configuration files of the Unique Entity Title module.

unique_entity_title.settings:
  type: config_object
  label: 'Unique entity title settings'

node.type.*.third_party.unique_entity_title:
  type: mapping
  label: 'Per-content type unique entity title settings'
  mapping:
    enabled:
      type: boolean
      label: 'Unique entity title'
